services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      args:
        PRISMA_CLIENT_OUTPUT: ${PRISMA_CLIENT_OUTPUT}
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
